[build]
  publish = "app/dist"
  command = "cd app && npm install && npm run build && cd ../functions && npm install"
  functions = "functions"

[dev]
  functions = "functions"
  
[functions]
  node_bundler = "esbuild"

# Enable automatic deploys from GitHub
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: blob: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https: data: blob:; frame-src 'self' https:; object-src 'none'"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# API endpoints - MUST come before the SPA catch-all rule
[[redirects]]
  from = "/api/projects/*"
  to = "/.netlify/functions/api-projects/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/blog/*"
  to = "/.netlify/functions/api-blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/certificates/*"
  to = "/.netlify/functions/api-certificates/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/services/*"
  to = "/.netlify/functions/api-services/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/testimonials/*"
  to = "/.netlify/functions/api-testimonials/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile"
  to = "/.netlify/functions/api-profile"
  status = 200
  force = true

[[redirects]]
  from = "/api/migrate"
  to = "/.netlify/functions/migrate-content"
  status = 200
  force = true

[[redirects]]
  from = "/api/setup-identity"
  to = "/.netlify/functions/setup-identity"
  status = 200
  force = true

[[redirects]]
  from = "/api/test-db"
  to = "/.netlify/functions/test-db-connection"
  status = 200
  force = true

[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200
  force = true

[[redirects]]
  from = "/api/init-db"
  to = "/.netlify/functions/init-db"
  status = 200
  force = true

# Consolidated content proxy redirects
[[redirects]]
  from = "/content/*"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true

# Registration page
[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

# Redirect admin access to secure page
[[redirects]]
  from = "/admin-login"
  to = "/admin-access.html"
  status = 200

# Redirect for image upload page
[[redirects]]
  from = "/image-upload"
  to = "/image-upload.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Redirect for image upload API
[[redirects]]
  from = "/images/upload"
  to = "/.netlify/functions/image-upload"
  status = 200
  force = true

# Protect admin panel with authentication
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Redirect unauthenticated admin requests
[[redirects]]
  from = "/admin/*"
  to = "/admin-access.html"
  status = 302

# Redirect rule to handle SPA routing - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200