[build]
  publish = "./"

# Redirect for SPA navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for Netlify CMS admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200