[build]
  publish = "app/dist"
  command = "cd app && npm install && npm run build"
  functions = "functions"

# Enable automatic deploys from GitHub
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"

# No plugins or functions are being used
# This is a simple static site

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: blob: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https: data: blob:; frame-src 'self' https:; object-src 'none'"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# Redirect admin access to secure page
[[redirects]]
  from = "/admin-login"
  to = "/admin-access.html"
  status = 200

# Redirect for image upload page
[[redirects]]
  from = "/image-upload"
  to = "/image-upload.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Redirect for image upload API
[[redirects]]
  from = "/images/upload"
  to = "/.netlify/functions/image-upload"
  status = 200
  force = true

# Protect admin panel with authentication
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Redirect unauthenticated admin requests
[[redirects]]
  from = "/admin/*"
  to = "/admin-access.html"
  status = 302

# Redirect rule to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for content files
[[redirects]]
  from = "/*/index.json"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/projects/*"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/services/*"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/certificates/*"
  to = "/.netlify/functions/content-proxy"
  status = 200
  force = true
