[build]
  publish = "/"
  command = "echo 'No build command'"

# Enable automatic deploys from GitHub
[build.environment]
  NODE_VERSION = "16"
  NETLIFY_USE_YARN = "true"

# Process content files on build
[[plugins]]
  package = "@netlify/plugin-functions"

[functions]
  directory = "functions"

# Generate and submit sitemap
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[plugins.inputs]
  baseUrl = "https://sharifabubakar.netlify.app"
  sitemapPath = "/sitemap.xml"
  providers = [
    "google",
    "bing"
  ]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://unpkg.com https://identity.netlify.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https:; frame-src 'self' https:; object-src 'none'"

# Redirect admin access to secure page
[[redirects]]
  from = "/admin-login"
  to = "/admin-access.html"
  status = 200

# Protect admin panel with authentication
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

# Redirect unauthenticated admin requests
[[redirects]]
  from = "/admin/*"
  to = "/admin-access.html"
  status = 302

# Redirect rule to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200