[build]
  publish = "/"
  command = "echo 'No build command'"

[[plugins]]
  package = "@netlify/plugin-functions"

[functions]
  directory = "functions"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[plugins.inputs]
  baseUrl = "https://sharifabubakar.netlify.app"
  sitemapPath = "/sitemap.xml"
  providers = [
    "google",
    "bing"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://unpkg.com https://identity.netlify.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https:; frame-src 'self' https:; object-src 'none'"

# Redirect rule to handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200