[build]
  publish = "/"
  command = "# no build command"

[build.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  framework = "#static"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"