backend:
  name: git-gateway
  branch: main

media_folder: "images/my-photos"
public_folder: "/images/my-photos"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string", hint: "FontAwesome icon class (e.g., fas fa-tasks)"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, default: false}
      - label: "Service Items"
        name: "items"
        widget: "list"
        field: {label: Item, name: item, widget: string}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "projects"
    label: "Portfolio Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Brief Description", name: "brief", widget: "string"}
      - {label: "Full Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["automation", "web", "data", "cybersecurity"]}
      - label: "Technologies Used"
        name: "tech"
        widget: "list"
        field: {label: Technology, name: technology, widget: string}
      - {label: "Project Link", name: "link", widget: "string", required: false, default: "#"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}