backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string", hint: "FontAwesome icon class (e.g., fas fa-tasks)"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, default: false}
      - label: "Service Items"
        name: "items"
        widget: "list"
        field: {label: Item, name: item, widget: string}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "projects"
    label: "Portfolio Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["automation", "web", "data", "cybersecurity"]}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Read Time", name: "readTime", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "site-settings"
    label: "Site Settings"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/settings/hero.yml"
        fields:
          - {label: "Profile Image", name: "profileImage", widget: "image", hint: "Your professional headshot"}
          - {label: "Background Image", name: "backgroundImage", widget: "image", hint: "Hero section background image"}
      
      - label: "About Section"
        name: "about"
        file: "content/settings/about.yml"
        fields:
          - {label: "About Image", name: "aboutImage", widget: "image", hint: "Image for the about section"}
      
      - label: "Logo & Branding"
        name: "branding"
        file: "content/settings/branding.yml"
        fields:
          - {label: "Logo", name: "logo", widget: "image", hint: "Your site logo"}
          - {label: "Favicon", name: "favicon", widget: "image", hint: "Site favicon (will be resized automatically)"}
          - {label: "Primary Color", name: "primaryColor", widget: "string", hint: "Primary brand color (hex code)"}
          - {label: "Secondary Color", name: "secondaryColor", widget: "string", hint: "Secondary brand color (hex code)"}