backend:
  name: git-gateway
  branch: main

media_folder: "app/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "app/public/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Brief Description", name: "brief", widget: "string"}
      - {label: "Full Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["virtual-assistant", "ai-tools", "web"]}
      - label: "Technologies Used"
        name: "tech"
        widget: "list"
        field: {label: "Technology", name: "technology", widget: "string"}
      - {label: "Project Link", name: "link", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 1}

  - name: "blog"
    label: "Blog Posts"
    folder: "app/public/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "YouTube Video ID", name: "youtubeId", widget: "string", required: false, hint: "Just the ID part from YouTube URL (e.g., dQw4w9WgXcQ)"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "services"
    label: "Services"
    folder: "app/public/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Icon", name: "icon", widget: "string", hint: "FontAwesome icon class (e.g., fa-user-tie)"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - label: "Service Items"
        name: "items"
        widget: "list"
        field: {label: "Item", name: "item", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "certificates"
    label: "Certificates"
    folder: "app/public/content/certificates"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Issuer", name: "issuer", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Order", name: "order", widget: "number", default: 1}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Profile"
        name: "profile"
        file: "app/public/content/settings/profile.json"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Profile Image", name: "image", widget: "image"}
          - {label: "Bio", name: "bio", widget: "text"}
          - {label: "Location", name: "location", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - {label: "GitHub", name: "github", widget: "string"}
          - {label: "WhatsApp", name: "whatsapp", widget: "string"}
          - {label: "CV File", name: "cv", widget: "file", required: false}

  - name: "testimonials"
    label: "Testimonials"
    folder: "app/public/content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
